language: node_js
node_js:
  - "node" # always use the latest; we are only using it as a test runner for now
cache: npm

env:
  global:
    - GOVERSION=1.11.2
    - GOPATH=
    - GOROOT=
    - PATH=~/go-${GOVERSION}/bin:~/go/bin:$PATH

before_install:
    - (cd ~ && curl -fsSLO https://dl.google.com/go/go${GOVERSION}.linux-amd64.tar.gz)
    - mkdir ~/go-${GOVERSION} && tar xf ~/go${GOVERSION}.linux-amd64.tar.gz -C ~/go-${GOVERSION} --strip-components 1

jobs:
  include:
    - stage: Tests
      name: lint
      script: npm run lint

    - name: unit tests
      script: make test

    - stage: Deploy
      script:
        # build and publish
        - make dist
        - npm publish @jkcfg/kubernetes
      if: tag IS present
